channels:
- conda-forge
dependencies:
- python=3.6.2
- pip:
  - azureml-core==1.0.81.1
  - azureml-defaults==1.0.81
  - azureml-telemetry==1.0.81.1
  - azureml-train-restclients-hyperdrive==1.0.81
  - azureml-train-core==1.0.81
name: azureml_2d6f32a8b5b445b7627fd1ae36599989
